commitizen:
  name: cz_conventional_commits
  tag_format: v$version
  update_changelog_on_bump: true
  version: 0.0.0
  version_scheme: semver
  bump_message: "bump: обновлена версия $current_version → $new_version\n\nОбновлён CHANGELOG.md"
