[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "elfparser"
version = "1.3.0"
description = "ELF BSS section inspector with DWARF parsing"
authors = [
    { name = "Uneld" }
]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "pyelftools",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["elfparser*"]
exclude = ["tests*", "test*", "build*", "dist*", "*.egg-info*"]

# Включить data файлы
[tool.setuptools.package-data]
elfparser = ["bin/*.exe"]